# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'RZBaseProject' do



pod 'AFNetworking', '~> 3.0'
pod 'MJExtension'
pod 'Masonry', '~> 0.6.4'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJRefresh', '~> 3.1.0'
pod 'IQKeyboardManager'
pod 'SVProgressHUD'
pod 'SDCycleScrollView','~> 1.64'
pod 'ReactiveObjC', '~> 3.0.0'
pod 'ZYCornerRadius', '~> 1.0.2'
pod 'YYKit'



end

