# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '9.0'
target 'RZBaseProject' do

# 网络请求
pod 'AFNetworking'
#pod 'AFNetworking', :subspecs => ['Serialization', 'Security', 'NSURLSession', 'Reachability']

# 网络监控
pod 'Reachability'

#字典转模型
pod 'MJExtension'
# 下拉刷新
pod 'MJRefresh'

# 图片加载
pod 'SDWebImage'

#用于适配
pod 'Masonry'

# YYKit
#pod 'YYKit'
pod 'YYImage'
pod 'YYText'
pod 'YYAsyncLayer'
pod 'YYCategories'
pod 'YYWebImage'

# 数据库
#pod 'FMDB'
pod 'BGFMDB', '~> 2.0.9'

# 蒙版
pod 'MBProgressHUD'

# 键盘管理
pod 'IQKeyboardManager'

# 无限轮播
pod 'SDCycleScrollView','>= 1.82'

# 切换滚动视图
pod 'JXCategoryView'

# 唯一设备标识
pod 'FCUUID'

# 全局滑动
pod 'FDFullscreenPopGesture'

# RAC
pod 'ReactiveObjC', '~> 3.0.0'

# 圆角
pod 'ZYCornerRadius', '~> 1.0.2'

# 播放器框架
pod 'ZFPlayer', '~> 4.0'
pod 'ZFPlayer/ControlView', '~> 4.0'
pod 'ZFPlayer/AVPlayer', '~> 4.0'
#pod 'ZFPlayer/ijkplayer', '~> 4.0'

# 日志框架
pod 'CocoaLumberjack'

# 动态创建模块化UI页面
pod 'LazyScroll'

# 二维码扫描
pod 'LBXScan', '~> 2.3'

# 广告页
pod 'XHLaunchAd'

# 不使用网络图片功能
pod 'HXPhotoPicker', '~> 3.1.7'

# 防崩溃框架
pod 'JJException'
pod 'Bugly'

# 封装Btn
pod 'JMButton', '~> 0.5'

# CC播放器
pod 'CCVodSDK'

end

